version: '3'

networks:
    bdnet:
      ipam:
        config:
          - subnet: 10.100.0.0/24

services:

    ratingservice:
        build: ./RatingService/
        #image: yasinsazid/dslab:rating1.0
        restart: always
        depends_on: 
            - mongodb
        networks:
            bdnet:
                ipv4_address: 10.100.0.4

    communicationservicedhaka:
        build: ./ComService/
        #image: yasinsazid/dslab:com1.0
        #ports: 
        #    - 7001:7001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.11
    
    rideservicedhaka:
        build: ./RideService/
        #image: yasinsazid/dslab:ride1.0
        restart: always
        depends_on: 
            - communicationservicedhaka
        environment: 
            - SERVERLOCATION=dhaka
        networks:
            bdnet:
                ipv4_address: 10.100.0.12

    nginxdhaka:
        build: ./Nginx/
        #image: yasinsazid/dslab:nginx1.0
        #ports: 
        #    - 8080:80
        depends_on: 
            - ratingservice
            - rideservicedhaka
        environment: 
            - API_V1=rideservicedhaka
            - API_V2=ratingservice
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.10

    communicationservicectg:
        build: ./ComService/
        #image: yasinsazid/dslab:com1.0
        #ports: 
        #    - 7001:7001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.21
    
    rideservicectg:
        build: ./RideService/
        #image: yasinsazid/dslab:ride1.0
        restart: always
        depends_on: 
            - communicationservicectg
        environment: 
            - SERVERLOCATION=ctg
        networks:
            bdnet:
                ipv4_address: 10.100.0.22

    nginxctg:
        build: ./Nginx/
        #image: yasinsazid/dslab:nginx1.0
        #ports: 
        #    - 8080:80
        depends_on: 
            - ratingservice
            - rideservicectg
        environment: 
            - API_V1=rideservicectg
            - API_V2=ratingservice
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.20

    mongodb:
        image: mongo
        ports: 
            - 27018:27017
        volumes:
            - mongodb_data_container:/data/db
        networks:
            bdnet:
                ipv4_address: 10.100.0.5
    
volumes:
    mongodb_data_container: