version: '3'

networks:
    bdnet:
      ipam:
        config:
          - subnet: 10.100.0.0/24

services:

    ratingService:
        #build: ./RatingService/
        image: yasinsazid/dslab:rating1.0
        restart: always
        depends_on: 
            - mongodb
        networks:
            bdnet:
                ipv4_address: 10.100.0.4

    communicationServiceDhaka:
        #build: ./CommunicationService/
        image: yasinsazid/dslab:com1.0
        #ports: 
        #    - 7001:7001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.11
    
    rideServiceDhaka:
        #build: ./RideSharingService/
        image: yasinsazid/dslab:ride1.0
        restart: always
        depends_on: 
            - communicationServiceDhaka
        environment: 
            - SERVERLOCATION=Dhaka
        networks:
            bdnet:
                ipv4_address: 10.100.0.12

    nginxDhaka:
        #build: ./nginx/
        image: yasinsazid/dslab:nginx1.0
        #ports: 
        #    - 8080:80
        depends_on: 
            - ratingService
            - rideServiceDhaka
        environment: 
            - API_V1=rideServiceDhaka
            - API_V2=ratingService
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.10

    communicationServiceCtg:
        #build: ./CommunicationService/
        image: yasinsazid/dslab:com1.0
        #ports: 
        #    - 7001:7001
        restart: always
        networks:
            bdnet:
                ipv4_address: 10.100.0.21
    
    rideServiceCtg:
        #build: ./RideSharingService/
        image: yasinsazid/dslab:ride1.0
        restart: always
        depends_on: 
            - communicationServiceCtg
        environment: 
            - SERVERLOCATION=Ctg
        networks:
            bdnet:
                ipv4_address: 10.100.0.22

    nginxCtg:
        #build: ./nginx/
        image: yasinsazid/dslab:nginx1.0
        #ports: 
        #    - 8080:80
        depends_on: 
            - ratingService
            - rideServiceCtg
        environment: 
            - API_V1=rideServiceCtg
            - API_V2=ratingService
        command: /bin/sh -c "envsubst < /etc/nginx/conf.d/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'" 
        networks:
            bdnet:
                ipv4_address: 10.100.0.20

    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        volumes:
            - mongodb_data_container:/data/db
    
volumes:
    mongodb_data_container: